logging:
  level:
    org.springframework.web: ERROR
    com.trackme: DEBUG
email: test@mkyong.com
thread-pool: 10
app:
  menus:
    - title: Home
      name: Home
      path: /
    - title: Login
      name: Login
      path: /login
  compiler:
    timeout: 5
    output-folder: /temp/
  error: /error/
  
Welcome:
  -Text: Welomce Mr Bond
  -number: 007
      
